Examples for oep12 provenance
oceanprotocol/OEPs pull request #112
Opened 2018-12-06 11:07 UTC by shark8me

This PR adds complete examples of provenance sections  included in the asset metadata for the use cases of

* initial publishing
* services creating derived assets

2018-12-06 11:19 UTC, diminator requested changes
I think the big question is "How can the provenance be trusted?"

- there are no descriptions on how the provenance is established
- how is integrity and soundness addressed?
- does this have cryptographic support that is verified at level1?

2018-12-06 12:16 UTC, diminator commented
related discussion https://github.com/oceanprotocol/OEPs/pull/111

2018-12-06 21:16 UTC, mikera commented
@diminator see my comments on #111 but from a design perspective I certainly agree that that we should be verifying provenance against service agreements wherever possible. 

Perhaps you can suggest a concrete way that the service agreement should be referenced in the provenance format to make this possible? We would obviously need corresponding functionality in the squid API to preform the actual verification.

From a collaborative process perspective, please either approve the PR or suggest an actionable improvement that @shark8me can incorporate. I would prefer to merge fast and iterate rather than having PRs stuck in limbo without an obvious next step.

2018-12-06 21:19 UTC, mikera commented on 12/examples/cleaned_dataset_metadata.json
> +              "prov:type": "ocn:service"
I believe this section should include a reference to the on-chain service agreement used to create the asset, if it exists?

2018-12-06 21:22 UTC, mikera commented on 12/examples/cleaned_dataset_metadata.json
> +              "ocn:did": "did:ocn:llongameabcd2938"
What does this did refer to? The individual administrator? If so this needs to be specified in the main OEP text, and we need to confirm if there is an design for individuals (as opposed to Ocean Agents) have a on-chain-registered DID.  

Suggest this is optional (we don't want to make it mandatory for individual users of Ocean to register DIDs), but if so that needs to be clearly specified.

2018-12-06 21:30 UTC, mikera commented on 12/examples/cleaned_dataset_metadata.json
> +          "ocn:ocn_abv2837282isk": {
Is this identifier simply an arbitrary ID valid only for the scope of this provenance  file? Should be specified how this behaves.

2018-12-06 21:31 UTC, mikera requested changes
Various comments to address. In particular, I think there needs to be a bit more formal definition / clarification what the different fields mean.

2018-12-11 02:18 UTC, shark8me commented on 12/examples/cleaned_dataset_metadata.json
> +              "prov:type": "ocn:service"
Agreed, will add that.

2018-12-11 02:34 UTC, shark8me commented on 12/examples/cleaned_dataset_metadata.json
> +              "prov:value": {
I'm inclined to have this as mandatory, so that the raw prov section should be interpretable directly rather that having to reference the metadata.

2018-12-11 02:38 UTC, shark8me commented on 12/examples/cleaned_dataset_metadata.json
> +              "prov:type":"ocn:dataset",
Again, it is useful from a PoV of the prov section being self-contained. The options will be defined in the validation tooling in a separate repo.

2018-12-11 02:44 UTC, shark8me commented on 12/examples/cleaned_dataset_metadata.json
> +          "ocn:ocn_abv2837282isk": {
This is the user account with an "ocn_" prefix, could be web3 or marketplace defined (length). Will be specified in the validation tooling.

I should  clarify that these examples are not mean to replace a proper spec & validation library.

2018-12-11 02:46 UTC, shark8me commented
@mikera I've added my comments. The formal spec & validation tooling, which specifies the mandatory/optional and type enums, will be a separate repo.

2019-08-14 14:44 UTC, kremalicious commented
Seems abandoned, requested changes were not provided, so closing.

2019-08-14 14:44 UTC, closed without merging

2019-08-15 03:09 UTC, mikera commented
Provenance has moved here - https://github.com/DEX-Company/DEPs/tree/master/12