Feature/oep14 assets registry
oceanprotocol/OEPs pull request #34
Opened 2018-05-07 10:02 UTC by aaitor

PR implementing #10

2018-05-08 04:11 UTC, gongf05 reviewed
The overall OEP looks very reasonable. One issue is the data structs and functions of the smart contracts may need some updates in the future implementation. It's really hard to finalize the design at this stage.  But I believe it is a good version to start with :)

2018-05-08 11:41 UTC, aaitor commented
I agree @gongf05 , the definition upfront of the Smart Contract interfaces, parameters, types, structs, etc. is quite difficult before to start. But I hope the current definition helps to show the overall idea, and we will adapt and refine during the development phase.

By the way, if the PR looks okay to you, I suggest to approve it :)
Having some approvals would allow to move on and start working in this development or alternative OEP's.

2018-05-08 14:37 UTC, gongf05 approved these changes
Great OEP to start with development.

2018-05-27 06:18 UTC, mikera requested changes
Some issues to resolve:

A) The TCR section in here seems like it is a little bit bolted on and incomplete. I suggest moving this to a separate OEP, independent of asset registration?
B) Implementation details seem to be creeping into API specification. Publishers registering assets shouldn't need to know about implementation details like the proposed Ocean DB or the particular solidity contracts used. I suggest keeping the OEP focused on the interface / API contracts
C) Need to be clear precisely which metadata is stored on-chain vs. what is stored elsewhere (related to the issue with 3/4/5). We can afford to detail the specifics of off-chain metadata later or in separate OEPs but the on-chain stuff must be solid with behaviour completely specified.

2018-05-27 06:27 UTC, mikera commented on 14/README.md
> +
This seems insufficient for a consumer to resolve information required to locate asset metadata or the marketplace from which it can be obtained? I think you need some form of marketplace / service provider ID?

2018-05-27 06:29 UTC, mikera commented on 14/README.md
> +
This seems like implementation detail? Does it need to be in the OEP? I'd expect all users to interact with the Ocean Protocol API as exposed by the Agent, so if we are to provide usage examples in the OEP it should be API calls at that level.

2018-05-27 06:31 UTC, mikera commented on 14/README.md
> +
I think this OEP should specify the Assets registration API, not implementation details of what happens with the proposed Ocean DB. In separate reviews, I have questioned the design of the Ocean DB approach so I suggest removing these references here pending resolution of broader architectural issues.

2018-05-27 06:34 UTC, mikera commented on 14/README.md
> +
I don't think ACL checks should always be on-chain? Better if these can be implemented off-chain, e.g. with calls to the appropriate service provider or marketplace that returns 403 if the ACL check fails.

2018-08-07 21:04 UTC, gongf05 commented
Updated the OEP-14 smart contracts for Assets Registry to make it consistent with our alpha version implementation.

2018-08-07 22:32 UTC, gongf05 commented on 14/README.md
> +### Updating Asset Provider
in alpha version, the owner is the provider of data asset. There is no need to update asset provider.

2018-12-07 09:18 UTC, aaitor commented
This OEP is out of date, closing.

2018-12-07 09:18 UTC, closed without merging