Update OEP7 to use DIDs for Actors, DID Paths for Assets
oceanprotocol/OEPs pull request #80
Opened 2018-10-11 05:03 UTC by mikera

The current OEP suggests that DID and DDOs should be registered for both Actors and Assets. This is a problem for serveral reasons:

- Assets are resources, not identities therefore are not a good fit for an Identity Management approach (they do not in general own their own public and private keys for example)
- Registering all Assets on-chain would be prohibitively expensive, given that a publisher may need to register thousands or even millions of Assets. 

This PR resolves these problems by:
- Retaining the DID/DDO approach for Actors / service providers
- Addressing Assets as DID paths under the DID of the relevant service provider (this is as recommended by the draft W3C spec: "A DID path SHOULD be used to address resources available via a DID service endpoint")

2018-10-15 03:49 UTC, mikera commented
Hi @aaitor , can you review this PR, see if you agree and if so merge? Thanks!

2018-10-15 06:23 UTC, aaitor requested changes
This was discussed a couple of weeks ago, also there is another PR about DID's with a different approach and different opinions.
As was said, we understand DID as a valid mechanism to identify not only Actors, also Assets.

2018-10-15 09:58 UTC, mikera commented
@Aitor this proposal does allow assets to be referenced via the DID Path approach recommended in the W3C spec, e.g. 

`did:ocn:cd2a3d9f938e13cd947ec05abc7fe734df8dd826/c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470`

Can you point me to the alternative proposal? Is it this PR? https://github.com/oceanprotocol/OEPs/pull/75

2018-10-15 10:16 UTC, aaitor commented
The proposal is OEP-7 and the PR to update this https://github.com/oceanprotocol/OEPs/pull/77

2018-10-15 10:18 UTC, diminator requested changes
This is a good start, but it's clear we need to have convergence on the following:
- abstract Identities that can have an DID (and not only look at actors, but also tribes and assets)
- consider the metadata network as a service network (ie a public or permissioned asset)
- connection between Identities and on-chain would be contracts such as Service Agreements, Verification and Curation Contracts

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +- Providing way to address Assets as resources managed under the DID of a relevant Actor
Assets can be viewed as a DID with guardianship
https://w3c-ccg.github.io/did-spec/#authorization-and-delegation

Assets are first-class citizens in the Ocean Network (~similar to smart contracts in ETH): 
- they are account holding (through Service Agreements)
- they can have an owner, but not need to (for self-steering assets and commons)

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +A DID for an Actor in Ocean takes the follwoing format:
~for and Actor~
I would remove this throughout the whole document

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +- Providing a way to cryptographically verify metadata for assets
I think metadata could be regarded as a service in the ocean network. Similar as storage, compute, ...

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +- Providing the ability to resolve a DDO (on-chain) for relevant Actors (especially service providers who need to expose API endpoints for the ecosystem
Change Actor through Identity throughout the whole document

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +Where the hexadecimal ID is the the ethereum account address of the Actor
Why the account and not a hash of the DDO (excluding the DID)

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +Where the hexadecimal ID is the the ethereum account address of the Actor
It will be important to see how to marshall the information that generates the unique identifier for integrity purpose

As a reference: this is how we compute the ID of a BigchainDB transaction:
https://github.com/bigchaindb/BEPs/tree/master/13

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +Where the two hexadecimal IDs are the ethereum account address of the Actor managing the Asset and ID of the Asset. The ID
We'll first want to figure out what are identities on the ocean network before tying them to ethereum account addresses

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +of the asset in turn is defined as the Hash (Keccak256?) of the Asset Metadata.
Or use multihash: https://github.com/multiformats/multihash

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +- It is possible to address the same Asset provided by multiple Service Providers (e.g. an asset is listed on multple marketplaces for sale).
This would be solved by Service Agreements where there is a 1-to-many relationship between an Asset identity and service agreements

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +- It is possible to extend this scheme to sub-Assets by extending the DID path
This is not true: the DID probably needs to be limited in length

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +- There is no requirement for Assets to be registered on-chain, allowing for efficient off-chain registration of Assets and associated Metadata
The main thing that's connecting assets to on-chain are the Service Agreements.
Metadata is regarded as a service

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +* Define a standard to identify Actors in Ocean using **Decentralized Identifiers (DID)**
~Actors~ Identities

2018-10-15 10:18 UTC, diminator commented on 7/README.md
> +* MATA AGENTS store the ASSET metadata off-chain
META

2018-10-15 11:11 UTC, mikera commented on 7/README.md
> +Where the hexadecimal ID is the the ethereum account address of the Actor
I believe DIDs for actors should be stable over time for a provider, i.e. you keep the same DID even if you update the DDO. On this basis, using the Ethereum account makes more sense than the DDO hash (which will change.... and technically should contain the DID anyway according to the spec)

2018-10-15 11:41 UTC, diminator commented on 7/README.md
> +Where the hexadecimal ID is the the ethereum account address of the Actor
False: A DDO might change while being versioned, and this would mean the Identity changed. Still the DDO related to that DID will exist. It decouples the account-dependency from the identity

2018-10-15 11:45 UTC, diminator commented on 7/README.md
> +Where the hexadecimal ID is the the ethereum account address of the Actor
You can make a DDO with an ethereum account, marshal, compute the DID and store the record.
This would be exactly the same operation. Event better, you would be able to connect multiple keys (ETH, BTC, ...) to a single DID and hence decouple from the dec. VM layer

2018-10-15 21:45 UTC, mikera commented on 7/README.md
> +- Providing the ability to resolve a DDO (on-chain) for relevant Actors (especially service providers who need to expose API endpoints for the ecosystem
Agreed. This does not appear to substantively change the design, and better to refer to Identities to avoid confusion with other Actors.

2018-10-15 21:47 UTC, mikera commented on 7/README.md
> +- Providing a way to cryptographically verify metadata for assets
Agreed. See the separate OEP (not yet numbered, but potentially OEP 15?) used to define the Meta API. https://github.com/oceanprotocol/OEPs/tree/feature/oepxxx-meta-api. @billbsing or myself will send a separate PR for this.

2018-10-15 21:47 UTC, mikera commented on 7/README.md
> +A DID for an Actor in Ocean takes the follwoing format:
Agreed

2018-10-15 21:53 UTC, mikera commented on 7/README.md
> +Where the hexadecimal ID is the the ethereum account address of the Actor
I suggest this as an approach because:
a) Any Actor wishing to register an Identity with a DID/DDO will need an Ethereum account anyway to pay the gas cost
b) It gives us a mechanism via verification of Ethereum transactions to control updates of DIDs/DDOs
c) It avoids the need to allocate different IDs



A different mechanism for allocating DIDs (e.g. hashing the initial version of the DDO without the DID) would be possible but don't see a motivating reason to add additional complexity here? There are issues with this approach:
- It won't be useful to verify the DDO directly because the DDO may be updated later
- Using the hash of the full DDO is technically impossible if we want to comply strictly with the DID spec because the DDO needs to contain the DID.
- There could potentially be DID collisions, e.g. multiple identities registering the same DDO (e.g. with nothing but identical endpoints)

2018-10-15 21:54 UTC, mikera commented on 7/README.md
> +Where the two hexadecimal IDs are the ethereum account address of the Actor managing the Asset and ID of the Asset. The ID
Added some proposed wording to define identities in this context. Other suggestions welcome

2018-10-15 21:55 UTC, mikera commented on 7/README.md
> +of the asset in turn is defined as the Hash (Keccak256?) of the Asset Metadata.
It there a motivating use case? It will keep implementations simpler if we can standardised on a hash function (this is mentioned as one of the requirements). I think an Ocean standard is helpful here.

2018-10-15 22:04 UTC, mikera commented on 7/README.md
> +- It is possible to address the same Asset provided by multiple Service Providers (e.g. an asset is listed on multple marketplaces for sale).
Provisionally agreed - assuming that the Service Agreement will need to specify the tribe / meta agent in any case so that provenance and metadata of the asset can be obtained? Is there a separate OEP for this?

2018-10-15 22:11 UTC, mikera commented on 7/README.md
> +- It is possible to extend this scheme to sub-Assets by extending the DID path
Current DID spec does not prescribe a limitation on length. We should probably implement an Ocean standard e.g. 2k. See e.g. https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

This should provide a standard upper bound without placing too much restriction on nested asset structure (about 30 levels deep if encoded in hex).

Have added a proposed 2k limit in the PR.

2018-10-15 22:12 UTC, mikera commented on 7/README.md
> +* Define a standard to identify Actors in Ocean using **Decentralized Identifiers (DID)**
Fixed

2018-10-16 08:41 UTC, diminator requested changes
I think we're closing in: main thing to resolve is how to construct the DID

2018-10-16 08:41 UTC, diminator commented on 7/README.md
> +- Providing a way to cryptographically verify metadata for assets
:100:

2018-10-16 08:41 UTC, diminator commented on 7/README.md
> +Where the two hexadecimal IDs are the ethereum account address of the Actor managing the Asset and ID of the Asset. The ID
I would propose the following for constructing a DDO and related DID:

a. fill in the fields related to the identity. `signature` and `did` fields are empty
b. compute the `signature` field: ie. sign the DDO after (a) and fill in the `signature` field
c. compute the `did` field: marshall and hash the DDO after (b) and fill in the `did` field

This way:
- the DID is an integrity check for the DDO
- the DDO is signed and cannot be replayed by non-holders of the private key
- the DDO and DID are independent of the underlying decentralized VM

an similar example can be found in the BigchainDB docs: https://github.com/bigchaindb/BEPs/tree/master/13#how-to-construct-a-transaction

2018-10-16 08:41 UTC, diminator commented on 7/README.md
> +- It is possible to address the same Asset provided by multiple Service Providers (e.g. an asset is listed on multple marketplaces for sale).
Under construction:  https://github.com/oceanprotocol/dev-ocean/blob/sla/version_01/doc/sla.md

The current thinking is that a Service Agreement is composed of conditions. and tribes will bring their own conditions (ie membership, permissions, payment, ...)

![image](https://user-images.githubusercontent.com/6178597/47001972-02c48580-d12c-11e8-853f-61ee3f21e9e9.png)

2018-10-16 08:41 UTC, diminator commented on 7/README.md
> +- It is possible to extend this scheme to sub-Assets by extending the DID path
If the DID is being used in Smart Contract languages like solidity, maybe it's more useful to look at `bytes32`?

https://solidity.readthedocs.io/en/v0.4.24/types.html#fixed-size-byte-arrays

2018-10-16 08:41 UTC, diminator commented on 7/README.md
> +- It is possible to extend this scheme to sub-Assets by extending the DID path
Of course we'll have to consider the chances on collisions when truncating, probably this can be overcome to some extent by hashing

2018-10-16 08:41 UTC, diminator commented on 7/README.md
> +
we'd probably can set limits on the DID root and paths separately

2018-10-16 08:51 UTC, diminator requested changes

2018-10-16 08:51 UTC, diminator commented on 7/README.md
> +- Providing way to address Assets as resources managed under the DID of a relevant Identity
Assets as DIDs with a guardian:
https://w3c-ccg.github.io/did-spec/#authorization-and-delegation

2018-10-23 10:48 UTC, mikera commented on 7/README.md
> +
Makes sense. Though perhaps you don't actually need to use deeply nested paths anyway: a read from `did:ocn:[provider ID]/[asset ID]/[sub-asset ID]` can probably just be compacted to `did:ocn:[provider ID]/[sub-asset ID]` since the hashing process effectively guarantees the sub-asset will be unique.

2018-10-23 10:58 UTC, mikera commented on 7/README.md
> +- Providing way to address Assets as resources managed under the DID of a relevant Identity
It seems assets are best modelled as "resources managed by an identity" (W3C DID spec 3.3: "A DID path SHOULD be used to address resources available via a DID service endpoint") rather than as entities which have delegated control to another entity (which would be more applicable e.g. in case of legal guardianship, or key recovery as suggested by W3C DID spec 4.5)

Does that make sense? Or do you have an alternative interpretation / design to suggest?

2018-10-31 10:42 UTC, mikera commented
@aitor @dimi What is blocking this from being merged?

Do you have additional concrete feedback or suggestions?

2018-10-31 11:36 UTC, diminator commented on 7/README.md
> +A DID/DDO is **mandatory** for any Identity wishing to offer Ocean Agent APIs to the ecosystem, because
Especially for assets DIDs in Service agreements

![image](https://user-images.githubusercontent.com/6178597/47785555-58428a00-dd09-11e8-92bb-744de0ca31f3.png)

2018-10-31 11:36 UTC, diminator commented on 7/README.md
> +
- a hash of the DDO

2018-10-31 11:36 UTC, diminator commented on 7/README.md
> +## Metadata Integrity
This would require a dedicated field in the DDO?

2018-11-01 06:03 UTC, mikera commented on 7/README.md
> +### Ocean standard endpoints
Agreed - I will move to a separate OEP

2018-11-01 08:32 UTC, mikera commented on 7/README.md
> +
We still have a requirement for a stable identifier, so using the hash of the DDO in general doesn't work as previously explained.

I agree the hash of the initial DDO (minus ID) could be used to generate an initial value for the stable identifier, but this seems pretty arbitrary and could have collisions. Have included as an an option - but we need to pick one soon!

2018-11-01 08:35 UTC, mikera commented on 7/README.md
> +## Metadata Integrity
I don't believe so. We propose to identify assets as follows:

`did:op:[Provider ID]/[Asset ID]`

Given the above string, you can validate the integrity of the asset metadata using the Asset ID. There isn't a need for anything in the DDO itself.

2018-11-06 18:03 UTC, sawlag commented on 7/README.md
> +- It is possible to address the same Asset provided by multiple Service Providers (e.g. an asset is listed on multple marketplaces for sale).
It might be worth ensuring these are a strict sub-set of the more general capabilities for this stream on data sharing agreement (DSA): 
https://spiral.imperial.ac.uk/handle/10044/1/21871  https://www.iit.cnr.it/sites/default/files/analyser.pdf
https://kar.kent.ac.uk/65817/1/An%20Architecture%20for%20Privacy-preserving%20Sharing%20of%20CTI%20with%203rd%20party%20Ana....pdf

The idea would be that the Ocean SAs are a part of wider potential attribute-based access control schemes (implemented by providers and in particular meeting various privacy needs).

Alignment with a strict subset of XACLM  might also be a good ploy: https://en.wikipedia.org/wiki/XACML .

2019-08-14 14:42 UTC, kremalicious commented
Seems abandoned, requested changes not provided until now, so closing.

2019-08-14 14:42 UTC, closed without merging